name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  get: 4.3.8
  google_sign_in: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
